services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: ui4monit-db
    environment:
      POSTGRES_USER: ui4monit
      POSTGRES_PASSWORD: ui4monit
      POSTGRES_DB: ui4monit
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - u4monit-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ui4monit"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ui4monit-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ui4monit
      DB_PASSWORD: ui4monit
      DB_NAME: ui4monit
      PORT: 8705
    ports:
      - "8705:8705"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - u4monit-net
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

#  frontend:
#    build: ./frontend
#    container_name: ui4monit-frontend
#    environment:
#      REACT_APP_API_URL: http://localhost:3001
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    command: npm start

volumes:
  postgres-data:

networks:
  u4monit-net:
    driver: bridge
